import type { Metadata } from "next";
import { Inter, Anuphan } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

// font inter
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// font Anuphan  use for thai font adn english font

const anuphan = Anuphan({
  variable: "--font-anuphan",
  subsets: ["thai", "latin"],
  weight: ["400", "500", "600", "700"],
});

// const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  title: {
    default: "AI Native App",
    template: "%s | AI Native App",
  },
  description: "AI-Native Application with Next.js 16 & Better Auth",
  keywords: ["Next.js", "AI", "Authentication", "Better Auth", "RAG"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" suppressHydrationWarning>
      <body
        className={`${anuphan.variable} ${inter.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
